/**
 * User Management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 * Contact: vtrusevich@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Object contains all required information for a user
 */
export interface Event {
    /**
     * Guid
     */
    guid?: string;
    /**
     * User's login
     */
    title: string;
    /**
     * User's password
     */
    description: string;
    /**
     * Confirm password
     */
    startTime: Date;
    /**
     * User's first name
     */
    duration: number;
    /**
     * User's last name
     */
    creatorId: number;
    /**
     * User's login
     */
    requirements: string;
    /**
     * User's avatar link
     */
    maxParticipantsCount: number;
}
