/**
 * User Management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 * Contact: vtrusevich@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Object contains all required information for a user
 */
export interface User {
    /**
     * Guid
     */
    guid?: string;
    /**
     * User's login
     */
    username: string;
    /**
     * User's password
     */
    password: string;
    /**
     * Confirm password
     */
    confirmPassword: string;
    /**
     * User's first name
     */
    firstName: string;
    /**
     * User's last name
     */
    lastName: string;
    /**
     * User's login
     */
    email: string;
    /**
     * User's avatar link
     */
    image: string;
    /**
     * User's role
     */
    role?: User.RoleEnum;
}
export namespace User {
    export type RoleEnum = 'ROLE_ADMIN' | 'ROLE_USER';
    export const RoleEnum = {
        ADMIN: 'ROLE_ADMIN' as RoleEnum,
        USER: 'ROLE_USER' as RoleEnum
    }
}
